// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sedwmymsmgykmunpqmdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlZHdteW1zbWd5a211bnBxbWR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzIwNTUsImV4cCI6MjA2NTUwODA1NX0.Jo9k0CuHreRd1fDOvjsPFb5A9YqvOkf7i_lY9DJc00A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);